// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableProviders() {
  return window['go']['main']['App']['GetAvailableProviders']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
