// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableProviders() {
  return window['go']['main']['App']['GetAvailableProviders']();
}

export function GetAvailableSymbols() {
  return window['go']['main']['App']['GetAvailableSymbols']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function FetchPrices(arg1) {
  return window['go']['main']['App']['FetchPrices'](arg1);
}

export function RefreshPrices() {
  return window['go']['main']['App']['RefreshPrices']();
}
