// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function GetAvailableProviders():Promise<Array<main.ProviderInfo>>;

export function GetConfig():Promise<config.Config>;

export function HideWindow():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;
