// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {providers} from '../models';
import {config} from '../models';
import {context} from '../models';

export function GetAvailableProviders():Promise<Array<main.ProviderInfo>>;

export function GetAvailableSymbols():Promise<Array<providers.SymbolInfo>>;

export function GetConfig():Promise<config.Config>;

export function GetContext():Promise<context.Context>;

export function HideWindow():Promise<void>;

export function QuitApp():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ShowWindow():Promise<void>;

export function FetchPrices(arg1:Array<string>):Promise<Array<providers.PriceData>>;

export function RefreshPrices():Promise<void>;
